# 2. Data Preparation

In this notebook we aim to do two things with the raw data `data/all_car_adverts.csv`.

1. Clean the data by fixing the issues we identified in our initial exploration.
2. Transform some of the columns such that they can be used in a machine learning model, i.e. Feature Engineering.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_original = pd.read_csv("../data/all_car_adverts.csv")
df = df_original.copy()
df.head()

,Unnamed: 0,make,model,variant,car_price,car_badges,car_title,car_sub_title,car_attention_grabber,car_specs,...,num_owner,ulez,full_service,part_service,part_warranty,full_dealership,first_year_road_tax,brand_new,finance_available,discounted
0,0,AC,Cobra,NaN,89995.0,NaN,AC Cobra,4.9 MK IV CRS 2dr,GENUINE AC COBRA CRS 522 BHP,"2001 (X reg), Convertible, 14,400 miles, 4.9L,...",...,5.0,0,0,0,0,0,0,0,0,0
1,1,AC,Cobra,NaN,92500.0,'',AC Cobra,378 - MkIV,PHYSICAL CAR!,"2019 (T reg), Convertible, 650 miles, Manual, ...",...,NaN,0,0,0,0,0,0,0,0,0
2,2,AC,Cobra,NaN,109995.0,'',AC Cobra,MK1V 212 SC. 3.5 V8 350 BHP LOTUS TWIN TURBO. ...,FULL CARBON FIBRE BODY.,"2000 (X reg), Convertible, 21,600 miles, 3.5L,...",...,3.0,0,0,0,0,0,0,0,0,0
3,3,AC,Cobra,NaN,124950.0,'',AC Cobra,302 MKIV 2dr,ABSOLUTELY STUNNING,"1989 (F reg), Convertible, 2,750 miles, Manual...",...,NaN,0,0,0,0,0,0,0,0,0
4,4,AC,Cobra,NaN,124950.0,'',AC Cobra,302 MKIV With Factory Lightweight Engine 5.0 2dr,'STAGE 3' SVO ENGINE,"1989 (E reg), Convertible, 15,142 miles, 5.0L,...",...,NaN,0,0,0,0,0,0,0,0,0

## 2.1. Data Wrangling
### 2.1.1. Column Naming

We can drop the `Unnamed: 0` column as this is just acting as an index, which we already have.

In [3]:
df.drop("Unnamed: 0", axis=1, inplace=True)
df.head()

,make,model,variant,car_price,car_badges,car_title,car_sub_title,car_attention_grabber,car_specs,car_seller,...,num_owner,ulez,full_service,part_service,part_warranty,full_dealership,first_year_road_tax,brand_new,finance_available,discounted
0,AC,Cobra,NaN,89995.0,NaN,AC Cobra,4.9 MK IV CRS 2dr,GENUINE AC COBRA CRS 522 BHP,"2001 (X reg), Convertible, 14,400 miles, 4.9L,...",Private seller,...,5.0,0,0,0,0,0,0,0,0,0
1,AC,Cobra,NaN,92500.0,'',AC Cobra,378 - MkIV,PHYSICAL CAR!,"2019 (T reg), Convertible, 650 miles, Manual, ...",Boss Motor Company Limited,...,NaN,0,0,0,0,0,0,0,0,0
2,AC,Cobra,NaN,109995.0,'',AC Cobra,MK1V 212 SC. 3.5 V8 350 BHP LOTUS TWIN TURBO. ...,FULL CARBON FIBRE BODY.,"2000 (X reg), Convertible, 21,600 miles, 3.5L,...",PREMIER GT LIMITED,...,3.0,0,0,0,0,0,0,0,0,0
3,AC,Cobra,NaN,124950.0,'',AC Cobra,302 MKIV 2dr,ABSOLUTELY STUNNING,"1989 (F reg), Convertible, 2,750 miles, Manual...",TOP 555 LIMITED,...,NaN,0,0,0,0,0,0,0,0,0
4,AC,Cobra,NaN,124950.0,'',AC Cobra,302 MKIV With Factory Lightweight Engine 5.0 2dr,'STAGE 3' SVO ENGINE,"1989 (E reg), Convertible, 15,142 miles, 5.0L,...",TOP 555 LIMITED,...,NaN,0,0,0,0,0,0,0,0,0

Then, as personal preference, we change the naming convention from `snake_case` to `PascalCase`. We also change `FeulType` to `FuelType` (fixing the typo) and rename `Ulez` and `ULEZ` as this is an abbreviation.

In [4]:
original_headers = list(df.columns.values)
renaming_dict = {h: h.replace("_", " ").title().replace(" ", "") for h in original_headers}
renaming_dict["feul_type"] = "FuelType"
renaming_dict["ulez"] = "ULEZ"

df.rename(columns=renaming_dict, inplace=True)
df.head()

,Make,Model,Variant,CarPrice,CarBadges,CarTitle,CarSubTitle,CarAttentionGrabber,CarSpecs,CarSeller,...,NumOwner,ULEZ,FullService,PartService,PartWarranty,FullDealership,FirstYearRoadTax,BrandNew,FinanceAvailable,Discounted
0,AC,Cobra,NaN,89995.0,NaN,AC Cobra,4.9 MK IV CRS 2dr,GENUINE AC COBRA CRS 522 BHP,"2001 (X reg), Convertible, 14,400 miles, 4.9L,...",Private seller,...,5.0,0,0,0,0,0,0,0,0,0
1,AC,Cobra,NaN,92500.0,'',AC Cobra,378 - MkIV,PHYSICAL CAR!,"2019 (T reg), Convertible, 650 miles, Manual, ...",Boss Motor Company Limited,...,NaN,0,0,0,0,0,0,0,0,0
2,AC,Cobra,NaN,109995.0,'',AC Cobra,MK1V 212 SC. 3.5 V8 350 BHP LOTUS TWIN TURBO. ...,FULL CARBON FIBRE BODY.,"2000 (X reg), Convertible, 21,600 miles, 3.5L,...",PREMIER GT LIMITED,...,3.0,0,0,0,0,0,0,0,0,0
3,AC,Cobra,NaN,124950.0,'',AC Cobra,302 MKIV 2dr,ABSOLUTELY STUNNING,"1989 (F reg), Convertible, 2,750 miles, Manual...",TOP 555 LIMITED,...,NaN,0,0,0,0,0,0,0,0,0
4,AC,Cobra,NaN,124950.0,'',AC Cobra,302 MKIV With Factory Lightweight Engine 5.0 2dr,'STAGE 3' SVO ENGINE,"1989 (E reg), Convertible, 15,142 miles, 5.0L,...",TOP 555 LIMITED,...,NaN,0,0,0,0,0,0,0,0,0

### 2.1.2. Data Types

A lot of the columns have not been assigned the correct data type. We correct these now.

In [5]:
df.dtypes

Make                       str
Model                      str
Variant                    str
CarPrice               float64
CarBadges                  str
CarTitle                   str
CarSubTitle                str
CarAttentionGrabber        str
CarSpecs                   str
CarSeller                  str
CarSellerRating        float64
CarSellerLocation          str
Year                       str
Reg                        str
BodyType                   str
Miles                  float64
EngineVol              float64
EngineSize             float64
EngineSizeUnit             str
Transmission               str
FuelType                   str
NumOwner               float64
ULEZ                     int64
FullService              int64
PartService              int64
PartWarranty             int64
FullDealership           int64
FirstYearRoadTax         int64
BrandNew                 int64
FinanceAvailable         int64
Discounted               int64
dtype: object

One of the first things we notice is the sheer amount of `int64` columns which actually represent boolean, or yes/no, flags. We convert these to the correct type.

In [6]:
# Check and change boolean columns to the correct type
def check_and_change(col_name):
    col = df[col_name]

    if not pd.api.types.is_integer_dtype(col):
        return False
    
    if col.max() > 1 or col.min() < 0:
        return False
    
    df[col_name] = df[col_name].astype(bool)
    return True


for col_name in df.columns.values:
    if check_and_change(col_name):
        print(f"{col_name} changed to boolean type")

df.head()

ULEZ changed to boolean type
FullService changed to boolean type
PartService changed to boolean type
PartWarranty changed to boolean type
FullDealership changed to boolean type
FirstYearRoadTax changed to boolean type
BrandNew changed to boolean type
FinanceAvailable changed to boolean type
Discounted changed to boolean type

,Make,Model,Variant,CarPrice,CarBadges,CarTitle,CarSubTitle,CarAttentionGrabber,CarSpecs,CarSeller,...,NumOwner,ULEZ,FullService,PartService,PartWarranty,FullDealership,FirstYearRoadTax,BrandNew,FinanceAvailable,Discounted
0,AC,Cobra,NaN,89995.0,NaN,AC Cobra,4.9 MK IV CRS 2dr,GENUINE AC COBRA CRS 522 BHP,"2001 (X reg), Convertible, 14,400 miles, 4.9L,...",Private seller,...,5.0,False,False,False,False,False,False,False,False,False
1,AC,Cobra,NaN,92500.0,'',AC Cobra,378 - MkIV,PHYSICAL CAR!,"2019 (T reg), Convertible, 650 miles, Manual, ...",Boss Motor Company Limited,...,NaN,False,False,False,False,False,False,False,False,False
2,AC,Cobra,NaN,109995.0,'',AC Cobra,MK1V 212 SC. 3.5 V8 350 BHP LOTUS TWIN TURBO. ...,FULL CARBON FIBRE BODY.,"2000 (X reg), Convertible, 21,600 miles, 3.5L,...",PREMIER GT LIMITED,...,3.0,False,False,False,False,False,False,False,False,False
3,AC,Cobra,NaN,124950.0,'',AC Cobra,302 MKIV 2dr,ABSOLUTELY STUNNING,"1989 (F reg), Convertible, 2,750 miles, Manual...",TOP 555 LIMITED,...,NaN,False,False,False,False,False,False,False,False,False
4,AC,Cobra,NaN,124950.0,'',AC Cobra,302 MKIV With Factory Lightweight Engine 5.0 2dr,'STAGE 3' SVO ENGINE,"1989 (E reg), Convertible, 15,142 miles, 5.0L,...",TOP 555 LIMITED,...,NaN,False,False,False,False,False,False,False,False,False

The other issue is that `NumOwner` is a float, when it should really be an integer.

In [7]:
df["NumOwner"] = df["NumOwner"].astype(pd.Int64Dtype())
df.head()

,Make,Model,Variant,CarPrice,CarBadges,CarTitle,CarSubTitle,CarAttentionGrabber,CarSpecs,CarSeller,...,NumOwner,ULEZ,FullService,PartService,PartWarranty,FullDealership,FirstYearRoadTax,BrandNew,FinanceAvailable,Discounted
0,AC,Cobra,NaN,89995.0,NaN,AC Cobra,4.9 MK IV CRS 2dr,GENUINE AC COBRA CRS 522 BHP,"2001 (X reg), Convertible, 14,400 miles, 4.9L,...",Private seller,...,5,False,False,False,False,False,False,False,False,False
1,AC,Cobra,NaN,92500.0,'',AC Cobra,378 - MkIV,PHYSICAL CAR!,"2019 (T reg), Convertible, 650 miles, Manual, ...",Boss Motor Company Limited,...,<NA>,False,False,False,False,False,False,False,False,False
2,AC,Cobra,NaN,109995.0,'',AC Cobra,MK1V 212 SC. 3.5 V8 350 BHP LOTUS TWIN TURBO. ...,FULL CARBON FIBRE BODY.,"2000 (X reg), Convertible, 21,600 miles, 3.5L,...",PREMIER GT LIMITED,...,3,False,False,False,False,False,False,False,False,False
3,AC,Cobra,NaN,124950.0,'',AC Cobra,302 MKIV 2dr,ABSOLUTELY STUNNING,"1989 (F reg), Convertible, 2,750 miles, Manual...",TOP 555 LIMITED,...,<NA>,False,False,False,False,False,False,False,False,False
4,AC,Cobra,NaN,124950.0,'',AC Cobra,302 MKIV With Factory Lightweight Engine 5.0 2dr,'STAGE 3' SVO ENGINE,"1989 (E reg), Convertible, 15,142 miles, 5.0L,...",TOP 555 LIMITED,...,<NA>,False,False,False,False,False,False,False,False,False

Further, `Year` is a string, when it should also be an integer. However, this is due to incorrect data entry on some columns. We change `Year` to an integer type and investigate further.

In [8]:
year_numeric = pd.to_numeric(df["Year"], errors="coerce")
not_year_numeric = year_numeric[year_numeric.isna()]
not_year_numeric.shape

(48080,)

There are 48k records with NaN entries into `Year`.

In [9]:
df.iloc[not_year_numeric.index]["Year"].unique()

<ArrowStringArray>
[                   'Hatchback',                  'Convertible',
                       'Saloon',                          'SUV',
                        'Coupe',                    'Automatic',
                       'Manual',                       'Estate',
                          'MPV',                       'Pickup',
                    'Combi Van',              'Car Derived Van',
 'First year road tax included',                    '101 miles',
                      'Minibus',                       'Camper']
Length: 16, dtype: str

These records clearly contain misinputted information into the `Year` column. Since these only represent a small portion of the dataset, we choose to remove them from the cleaned dataset. This is because we assume that `Year` will be some indicator of pricing, which is what we are attempting to predict.

In [10]:
df["Year"] = year_numeric
df = df.iloc[year_numeric.index]
df.head()

,Make,Model,Variant,CarPrice,CarBadges,CarTitle,CarSubTitle,CarAttentionGrabber,CarSpecs,CarSeller,...,NumOwner,ULEZ,FullService,PartService,PartWarranty,FullDealership,FirstYearRoadTax,BrandNew,FinanceAvailable,Discounted
0,AC,Cobra,NaN,89995.0,NaN,AC Cobra,4.9 MK IV CRS 2dr,GENUINE AC COBRA CRS 522 BHP,"2001 (X reg), Convertible, 14,400 miles, 4.9L,...",Private seller,...,5,False,False,False,False,False,False,False,False,False
1,AC,Cobra,NaN,92500.0,'',AC Cobra,378 - MkIV,PHYSICAL CAR!,"2019 (T reg), Convertible, 650 miles, Manual, ...",Boss Motor Company Limited,...,<NA>,False,False,False,False,False,False,False,False,False
2,AC,Cobra,NaN,109995.0,'',AC Cobra,MK1V 212 SC. 3.5 V8 350 BHP LOTUS TWIN TURBO. ...,FULL CARBON FIBRE BODY.,"2000 (X reg), Convertible, 21,600 miles, 3.5L,...",PREMIER GT LIMITED,...,3,False,False,False,False,False,False,False,False,False
3,AC,Cobra,NaN,124950.0,'',AC Cobra,302 MKIV 2dr,ABSOLUTELY STUNNING,"1989 (F reg), Convertible, 2,750 miles, Manual...",TOP 555 LIMITED,...,<NA>,False,False,False,False,False,False,False,False,False
4,AC,Cobra,NaN,124950.0,'',AC Cobra,302 MKIV With Factory Lightweight Engine 5.0 2dr,'STAGE 3' SVO ENGINE,"1989 (E reg), Convertible, 15,142 miles, 5.0L,...",TOP 555 LIMITED,...,<NA>,False,False,False,False,False,False,False,False,False

`NumOwner` still contains N/A entries. However, we will keep the column as is for now. In exploratory analysis, we will identify if there are is a pattern amongst listings with
N/A owners.

### 2.1.3. Is `CarTitle` redundant?

Some of the columns in the dataset are potentially redundant. Namely `CarSpecs`, which is simply a retelling of the data in the dataset in a human-readable format. However, we suspect that `CarTitle` and `CarSubTitle` may also be redudnant too.

We suspect that `CarTitle` is simply a concatenation of the `Make`, `Model`, `Variant` columns.

In [11]:
def normalise(s):
    return (
        s.astype(str)
        .str.lower()
        .str.replace(r"\s+", " ", regex=True)
        .str.strip()
    )

expected_title = normalise(
    df["Make"].astype(str) + " " + df["Model"].astype(str) + " " + df["Variant"].astype(str).fillna("")
)
actual = normalise(df["CarTitle"])

matches = expected_title == actual
matches.mean()

np.float64(0.0036764346525653183)

In [12]:
df[~matches]

,Make,Model,Variant,CarPrice,CarBadges,CarTitle,CarSubTitle,CarAttentionGrabber,CarSpecs,CarSeller,...,NumOwner,ULEZ,FullService,PartService,PartWarranty,FullDealership,FirstYearRoadTax,BrandNew,FinanceAvailable,Discounted
6,AC,NaN,MK IV,124950.0,'',AC Cobra,302 MKIV 2dr,ABSOLUTELY STUNNING,"1989 (F reg), Convertible, 2,750 miles, Manual...",TOP 555 LIMITED,...,<NA>,False,False,False,False,False,False,False,False,False
7,AC,NaN,MK IV CRS,89995.0,NaN,AC Cobra,4.9 MK IV CRS 2dr,GENUINE AC COBRA CRS 522 BHP,"2001 (X reg), Convertible, 14,400 miles, 4.9L,...",Private seller,...,5,False,False,False,False,False,False,False,False,False
8,Abarth,124 Spider,GT,24275.0,"'Good price', 'Approved used', 'Finance availa...",Abarth 124 Spider,1.4 T MultiAir 2dr Auto,Reserve Online for \xa399,"2019 (19 reg), Convertible, 10,313 miles, 1.4L...",Glyn Hopkin Fiat and MG Milton Keynes,...,2,True,False,False,False,False,False,False,True,False
9,Abarth,124 Spider,GT,24275.0,"'Great price', 'Approved used', 'Finance avail...",Abarth 124 Spider,1.4 T MultiAir 2dr Auto,Reserve Online for \xa399,"2019 (19 reg), Convertible, 10,313 miles, 1.4L...",Glyn Hopkin Fiat and MG Milton Keynes,...,2,True,False,False,False,False,False,False,True,False
10,Abarth,124 Spider,GT,25000.0,'Finance available',Abarth 124 Spider,1.4 MultiAir GT Roadster Auto Euro 6 2dr,Rare 1 of 50 GT cars in the UK,"2018 (68 reg), Convertible, 11,500 miles, 1.4L...",Private seller,...,2,True,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818438,Volvo,XC90,h T8,82460.0,'Brand new',Volvo XC90,2.0h T8 Recharge 18.8kWh Ultimate Bright SUV 5...,Available in only 4 weeks!,"SUV, 2.0L, 455PS, Automatic, Petrol Plug-in Hy...",Volvo Online,...,<NA>,True,False,False,True,False,True,True,False,False
818439,Volvo,XC90,h T8,82640.0,'Brand new',Volvo XC90,2.0h T8 Recharge 18.8kWh Ultimate Dark Auto 4W...,In Stock Available NOW!!,"2022, SUV, 2.0L, 455PS, Automatic, Petrol Plug...",Caffyns Volvo Eastbourne,...,<NA>,True,False,False,True,False,True,True,False,False
818440,Volvo,XC90,h T8,82640.0,'Brand new',Volvo XC90,2.0h T8 Recharge 18.8kWh Ultimate Dark SUV 5dr...,Available in only 5 weeks!,"SUV, 2.0L, 455PS, Automatic, Petrol Plug-in Hy...",Volvo Online,...,<NA>,True,False,False,True,False,True,True,False,False
818441,Volvo,XC90,h T8,82640.0,'Brand new',Volvo XC90,2.0h T8 Recharge 18.8kWh Ultimate Dark Auto 4W...,Available in only 4 weeks!,"SUV, 2.0L, 455PS, Automatic, Petrol Plug-in Hy...",Volvo Online,...,<NA>,True,False,False,True,False,True,True,False,False
818454,Yamaha,NaN,Unlisted,22990.0,'Finance available',Yamaha YXZ 1000R,NaN,2022 PLATE WITH 772KM,"2022 (22 reg), 480 miles",PM Car Sales,...,<NA>,False,False,False,False,False,False,False,True,False

So, we find that `CarTitle` is not simple a concatenation of `Make`, `Model` and `Variant`. Notably, there are cases in which the variant is not mentioned in the title. In investigating this, we also discovered that the model column is incomplete. We believe that we are able to use the `CarTitle` to recover this. The `CarTitle` is at least a concatenation of `Make` and `Model`. Therefore, if two records have the same title, then they have the same make and model.

However, we can also conclude that `CarTitle` is most likely data related to the listing, rather than data related to the car itself. This is a useful conclusion to reach when it comes to feature engineering. However, at this stage, we will use it to recover some data.

In [13]:
missing_model = df[pd.isna(df["Model"])]
missing_model

,Make,Model,Variant,CarPrice,CarBadges,CarTitle,CarSubTitle,CarAttentionGrabber,CarSpecs,CarSeller,...,NumOwner,ULEZ,FullService,PartService,PartWarranty,FullDealership,FirstYearRoadTax,BrandNew,FinanceAvailable,Discounted
6,AC,NaN,MK IV,124950.0,'',AC Cobra,302 MKIV 2dr,ABSOLUTELY STUNNING,"1989 (F reg), Convertible, 2,750 miles, Manual...",TOP 555 LIMITED,...,<NA>,False,False,False,False,False,False,False,False,False
7,AC,NaN,MK IV CRS,89995.0,NaN,AC Cobra,4.9 MK IV CRS 2dr,GENUINE AC COBRA CRS 522 BHP,"2001 (X reg), Convertible, 14,400 miles, 4.9L,...",Private seller,...,5,False,False,False,False,False,False,False,False,False
5140,Alpine,NaN,Color Edition,53995.0,'Finance available',Alpine A110,1.8 COLOUR EDITION 2d 292 BHP ***VAT QUALIFYIN...,"SUNFLOWER YELLOW, CARBON ROOF","2021 (21 reg), Coupe, 1,000 miles, 1.8L, 292PS...",KTR Car Sales,...,2,True,False,False,False,False,False,False,True,False
5141,Alpine,NaN,GT,62840.0,'Brand new',Alpine A110,1.8 Turbo GT DCT Euro 6 2dr,Order now for December,"Coupe, 1.8L, 300PS, Automatic, Petrol, First y...",Martins Alpine Winchester,...,<NA>,True,False,False,True,False,True,True,False,False
5142,Alpine,NaN,GT,63392.0,'Brand new',Alpine A110,1.8 Turbo GT DCT Euro 6 2dr,Abyss GT due October,"Coupe, 1.8L, 300PS, Automatic, Petrol, First y...",Alpine Centre Orpington,...,<NA>,True,False,False,True,False,True,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
612043,Reo,NaN,Unlisted,12000.0,'',REO Flying Cloud,LHD REO FLYING CLOUD 1931 4 DR SEDAN 1931 clas...,STORED IN BARN FOR 32 YEARS,"1990 (G reg), 15,000 miles, 4.3L, Petrol",Longmans Motors,...,<NA>,False,False,False,False,False,False,False,False,False
612045,Replica,NaN,Unlisted,69990.0,'',Replica Cobra,SUPERPERFORMANCE 7.0 LITRE BIG BLOCK,"7 LITRE BIG BLOCK, Mk-111","2001 (X reg), 8,000 miles",Sovereign Cars,...,<NA>,False,False,False,False,False,False,False,False,False
649955,Shelby,NaN,Unlisted,79995.0,'',Shelby Cobra,NaN,MICHEL MOTORSPORT COMPETITION,"1987 (D reg), 5,190 miles",Peter Nash Specialist Cars,...,<NA>,False,False,False,False,False,False,False,False,False
654124,Sunbeam,NaN,Unlisted,3995.0,'',Sunbeam Alpine,NaN,1967 RESTORATION PROJECT,"1967 (E reg), 80,000 miles",Heritage and Performance,...,<NA>,False,False,False,False,False,False,False,False,False
818454,Yamaha,NaN,Unlisted,22990.0,'Finance available',Yamaha YXZ 1000R,NaN,2022 PLATE WITH 772KM,"2022 (22 reg), 480 miles",PM Car Sales,...,<NA>,False,False,False,False,False,False,False,True,False

We use `CarTitle` to fix the missing model issue as follows:

1. For each `CarTitle` in the dataframe above, check if there a record which has the same `CarTitle` and also includes a `Model`
2. If so, then replace NaN with that model
3. Check what is remaining afterwards, and reassess

In [14]:
# Get a list of title -> models
title_model = df.groupby("CarTitle")["Model"].first()
title_model

CarTitle
AC Cobra                        Cobra
AK Cobra                        Cobra
Abarth 124                 124 Spider
Abarth 124 SPIDER          124 Spider
Abarth 124 Spider          124 Spider
                            ...
Westfield Seight               SEight
Westfield Sport                 Sport
Wolseley 1500                    1500
Yamaha YXZ 1000R            Yxz 1000r
Zimmer Golden Spirit    Golden Spirit
Name: Model, Length: 3946, dtype: str

In [15]:
# Replace NaN models using this data
df.loc[df["Model"].isna(), "Model"] = (
    df.loc[df["Model"].isna(), "CarTitle"].map(title_model)
)

df.head()

,Make,Model,Variant,CarPrice,CarBadges,CarTitle,CarSubTitle,CarAttentionGrabber,CarSpecs,CarSeller,...,NumOwner,ULEZ,FullService,PartService,PartWarranty,FullDealership,FirstYearRoadTax,BrandNew,FinanceAvailable,Discounted
0,AC,Cobra,NaN,89995.0,NaN,AC Cobra,4.9 MK IV CRS 2dr,GENUINE AC COBRA CRS 522 BHP,"2001 (X reg), Convertible, 14,400 miles, 4.9L,...",Private seller,...,5,False,False,False,False,False,False,False,False,False
1,AC,Cobra,NaN,92500.0,'',AC Cobra,378 - MkIV,PHYSICAL CAR!,"2019 (T reg), Convertible, 650 miles, Manual, ...",Boss Motor Company Limited,...,<NA>,False,False,False,False,False,False,False,False,False
2,AC,Cobra,NaN,109995.0,'',AC Cobra,MK1V 212 SC. 3.5 V8 350 BHP LOTUS TWIN TURBO. ...,FULL CARBON FIBRE BODY.,"2000 (X reg), Convertible, 21,600 miles, 3.5L,...",PREMIER GT LIMITED,...,3,False,False,False,False,False,False,False,False,False
3,AC,Cobra,NaN,124950.0,'',AC Cobra,302 MKIV 2dr,ABSOLUTELY STUNNING,"1989 (F reg), Convertible, 2,750 miles, Manual...",TOP 555 LIMITED,...,<NA>,False,False,False,False,False,False,False,False,False
4,AC,Cobra,NaN,124950.0,'',AC Cobra,302 MKIV With Factory Lightweight Engine 5.0 2dr,'STAGE 3' SVO ENGINE,"1989 (E reg), Convertible, 15,142 miles, 5.0L,...",TOP 555 LIMITED,...,<NA>,False,False,False,False,False,False,False,False,False

In [16]:
# Check what's still NaN
missing_model = df[pd.isna(df["Model"])]
missing_model

,Make,Model,Variant,CarPrice,CarBadges,CarTitle,CarSubTitle,CarAttentionGrabber,CarSpecs,CarSeller,...,NumOwner,ULEZ,FullService,PartService,PartWarranty,FullDealership,FirstYearRoadTax,BrandNew,FinanceAvailable,Discounted
5172,Alpine,NaN,Legende GT,61975.0,'Finance available',Alpine A110 Legende GT,1.8 Turbo Legende GT DCT Euro 6 2dr,"NO. 6 of 300, Full PPF","2022 (71 reg), Coupe, 1,800 miles, 1.8L, 292BH...",Kaaimans International,...,<NA>,True,False,False,False,False,False,False,True,False
654124,Sunbeam,NaN,Unlisted,3995.0,'',Sunbeam Alpine,NaN,1967 RESTORATION PROJECT,"1967 (E reg), 80,000 miles",Heritage and Performance,...,<NA>,False,False,False,False,False,False,False,False,False

Almost all of the `Model` data was recovered using existing records and the `CarTitle` variable. Only two rows remain with NaN `Model`'s, and the `Model` can easily be identified by eye

- Alpine A110 Legende GT clearly has model "A110", since "Legende GT" is the value of its `Variant`.
- Sunbeam Alpine clearly has model "Alpine" since "Sunbeam" is the `Make`, and there is no `Variant`.

So we can fill these in by hand.

In [17]:
# Manually replace Models for the rows
df.loc[5172, "Model"] = "A110"
df.loc[654124, "Model"] = "Alpine"

In [18]:
# Check what's still NaN
missing_model = df[pd.isna(df["Model"])]
missing_model

Empty DataFrame
Columns: [Make, Model, Variant, CarPrice, CarBadges, CarTitle, CarSubTitle, CarAttentionGrabber, CarSpecs, CarSeller, CarSellerRating, CarSellerLocation, Year, Reg, BodyType, Miles, EngineVol, EngineSize, EngineSizeUnit, Transmission, FuelType, NumOwner, ULEZ, FullService, PartService, PartWarranty, FullDealership, FirstYearRoadTax, BrandNew, FinanceAvailable, Discounted]
Index: []

[0 rows x 31 columns]

We have managed to recover all `Model` data using the `CarTitle` column. We check if we need to do the same for `Make`.

In [19]:
df[df["Make"].isna()]

Empty DataFrame
Columns: [Make, Model, Variant, CarPrice, CarBadges, CarTitle, CarSubTitle, CarAttentionGrabber, CarSpecs, CarSeller, CarSellerRating, CarSellerLocation, Year, Reg, BodyType, Miles, EngineVol, EngineSize, EngineSizeUnit, Transmission, FuelType, NumOwner, ULEZ, FullService, PartService, PartWarranty, FullDealership, FirstYearRoadTax, BrandNew, FinanceAvailable, Discounted]
Index: []

[0 rows x 31 columns]

The `Make` is present for all records.

We shall not do the same for `Variant`. This is because we do not see `Variant` as a reliable variable in the dataset for the following reasons:

- It is frequently missing
- `CarTitle` is associated with the listing and so wording isn't standardised. Thus, it's hard to do it in a way which is automatic
- Manual methods are time consuming and subjective
- There are even some cases where the `Variant` is not mentioned in the `CarTitle`, so even a perfect method could not recover all cases

However, we will still clean the column, since there are instances of an "Unlisted" string which we will replace with NaN now.

In [20]:
df[df["Variant"] == "Unlisted"].shape

(37, 31)

In [21]:
df.loc[df["Variant"] == "Unlisted", "Variant"] = pd.NA
df[df["Variant"] == "Unlisted"].shape

(0, 31)

### 2.1.4. Replacing Incomplete Data with NaN

We notice that the `CarBadges` column contains empty strings. We replace these with N/A. We also remove the quotation marks '' where necessary.

In [22]:
# Remove quotes
df["CarBadges"] = df["CarBadges"].str.replace("'", "")
df.head()

,Make,Model,Variant,CarPrice,CarBadges,CarTitle,CarSubTitle,CarAttentionGrabber,CarSpecs,CarSeller,...,NumOwner,ULEZ,FullService,PartService,PartWarranty,FullDealership,FirstYearRoadTax,BrandNew,FinanceAvailable,Discounted
0,AC,Cobra,NaN,89995.0,NaN,AC Cobra,4.9 MK IV CRS 2dr,GENUINE AC COBRA CRS 522 BHP,"2001 (X reg), Convertible, 14,400 miles, 4.9L,...",Private seller,...,5,False,False,False,False,False,False,False,False,False
1,AC,Cobra,NaN,92500.0,,AC Cobra,378 - MkIV,PHYSICAL CAR!,"2019 (T reg), Convertible, 650 miles, Manual, ...",Boss Motor Company Limited,...,<NA>,False,False,False,False,False,False,False,False,False
2,AC,Cobra,NaN,109995.0,,AC Cobra,MK1V 212 SC. 3.5 V8 350 BHP LOTUS TWIN TURBO. ...,FULL CARBON FIBRE BODY.,"2000 (X reg), Convertible, 21,600 miles, 3.5L,...",PREMIER GT LIMITED,...,3,False,False,False,False,False,False,False,False,False
3,AC,Cobra,NaN,124950.0,,AC Cobra,302 MKIV 2dr,ABSOLUTELY STUNNING,"1989 (F reg), Convertible, 2,750 miles, Manual...",TOP 555 LIMITED,...,<NA>,False,False,False,False,False,False,False,False,False
4,AC,Cobra,NaN,124950.0,,AC Cobra,302 MKIV With Factory Lightweight Engine 5.0 2dr,'STAGE 3' SVO ENGINE,"1989 (E reg), Convertible, 15,142 miles, 5.0L,...",TOP 555 LIMITED,...,<NA>,False,False,False,False,False,False,False,False,False

In [23]:
# Replace empty strings with NaN
df.loc[df["CarBadges"].str.strip().str.len() == 0, "CarBadges"] = df[df["CarBadges"].str.strip().str.len() == 0].map(lambda x: pd.NA)
df.head()

,Make,Model,Variant,CarPrice,CarBadges,CarTitle,CarSubTitle,CarAttentionGrabber,CarSpecs,CarSeller,...,NumOwner,ULEZ,FullService,PartService,PartWarranty,FullDealership,FirstYearRoadTax,BrandNew,FinanceAvailable,Discounted
0,AC,Cobra,NaN,89995.0,NaN,AC Cobra,4.9 MK IV CRS 2dr,GENUINE AC COBRA CRS 522 BHP,"2001 (X reg), Convertible, 14,400 miles, 4.9L,...",Private seller,...,5,False,False,False,False,False,False,False,False,False
1,AC,Cobra,NaN,92500.0,NaN,AC Cobra,378 - MkIV,PHYSICAL CAR!,"2019 (T reg), Convertible, 650 miles, Manual, ...",Boss Motor Company Limited,...,<NA>,False,False,False,False,False,False,False,False,False
2,AC,Cobra,NaN,109995.0,NaN,AC Cobra,MK1V 212 SC. 3.5 V8 350 BHP LOTUS TWIN TURBO. ...,FULL CARBON FIBRE BODY.,"2000 (X reg), Convertible, 21,600 miles, 3.5L,...",PREMIER GT LIMITED,...,3,False,False,False,False,False,False,False,False,False
3,AC,Cobra,NaN,124950.0,NaN,AC Cobra,302 MKIV 2dr,ABSOLUTELY STUNNING,"1989 (F reg), Convertible, 2,750 miles, Manual...",TOP 555 LIMITED,...,<NA>,False,False,False,False,False,False,False,False,False
4,AC,Cobra,NaN,124950.0,NaN,AC Cobra,302 MKIV With Factory Lightweight Engine 5.0 2dr,'STAGE 3' SVO ENGINE,"1989 (E reg), Convertible, 15,142 miles, 5.0L,...",TOP 555 LIMITED,...,<NA>,False,False,False,False,False,False,False,False,False

### 2.1.5. Column Standardisation

The `Reg` column is a string which always contains the word 'reg' at the end. This word is unnecessary and is removed. We also ensure that all entries are upper case.

In [24]:
df["Reg"] = df["Reg"].str.replace(" reg", "").str.upper()
df.head(20)[["Make", "Model", "Reg", "Year"]]

      Make       Model Reg    Year
0       AC       Cobra   X  2001.0
1       AC       Cobra   T  2019.0
2       AC       Cobra   X  2000.0
3       AC       Cobra   F  1989.0
4       AC       Cobra   E  1989.0
5       AC       Cobra  22  2022.0
6       AC       Cobra   F  1989.0
7       AC       Cobra   X  2001.0
8   Abarth  124 Spider  19  2019.0
9   Abarth  124 Spider  19  2019.0
10  Abarth  124 Spider  68  2018.0
11  Abarth  124 Spider  18  2018.0
12  Abarth  124 Spider  67  2017.0
13  Abarth  124 Spider  67  2018.0
14  Abarth  124 Spider  18  2018.0
15  Abarth  124 Spider  67  2017.0
16  Abarth  124 Spider  18  2018.0
17  Abarth  124 Spider  67  2017.0
18  Abarth  124 Spider  18  2018.0
19  Abarth  124 Spider  67  2017.0

We also standardise the following columns by ensuring all data is given in title case:

- `CarSellerLocation`
- `Transmission`
- `BodyType` 
- `FuelType`

In [25]:
to_title_case = ["CarSellerLocation", "Transmission", "BodyType", "FuelType"]

for column in to_title_case:
    df[column] = df[column].str.title()

df[to_title_case].head(20)

   CarSellerLocation Transmission     BodyType FuelType
0            Watford       Manual  Convertible   Petrol
1            Chesham       Manual  Convertible   Petrol
2         Pulborough       Manual  Convertible   Petrol
3             Oakham       Manual  Convertible   Petrol
4             Oakham       Manual  Convertible   Petrol
5            Chesham       Manual  Convertible   Petrol
6             Oakham       Manual  Convertible   Petrol
7            Watford       Manual  Convertible   Petrol
8      Milton Keynes    Automatic  Convertible   Petrol
9      Milton Keynes    Automatic  Convertible   Petrol
10            Forres    Automatic  Convertible   Petrol
11         Willesden       Manual  Convertible   Petrol
12          Alcester       Manual  Convertible   Petrol
13        Nottingham       Manual  Convertible   Petrol
14         Willesden       Manual  Convertible   Petrol
15        Portsmouth       Manual  Convertible   Petrol
16          Petworth       Manual  Convertible   Petrol
17           Newport    Automatic  Convertible   Petrol
18         Willesden       Manual  Convertible   Petrol
19         Willesden       Manual  Convertible   Petrol

### 2.1.5. Cleaning Summary

In this section we have cleaned the data by performing the following:

- Renaming the columns to fit a preferred naming convention
- Fixed a typo in one of the columns
- Examined `CarTitle` and used it to recover missing `Model` information both automatically and manually
- Tidied the `CarBadges` column
- We standardised some of the other columns, e.g. making sure all strings are in title case in location and transmission columns, ensuring `Reg` is always capitalised, and does not include the 'reg' suffix.

We save this clean dataset as `data/clean_car_adverts.parquet`.

In [26]:
df.to_csv("../data/clean_car_adverts.parquet")

## 2.2. Feature Engineering

In this section, we clarify what we are attempting to model and select the columns which we are certain will be used for modelling or wish to analyse further before coming to a decision. In addition, we try to "minimise" the dataset. For example, we will take the `EngineSizeUnit` and `EngineSize` columns and attempt to unify them by converting all `EngineSize` measurements into the same units.

### 2.2.1. Problem Definition

We wish to use the car specifications to attempt to predict the selling price of the car. In simpler terms, we wish to use the data which is used to create the advert, not the advert itself. This means that we do not wish to use columns such as `CarAttentionGrabber` and `CarSeller`.

One column which sits in a bit of a grey area is `CarSellerLocation`, since while it is technically tied to the listing rather than being an intrinsic feature of the car. Geographical location could play into some local supply-demand dynamics. Therefore, we shall leave this column.

This is the complete list of columns dropped due to not being relevant for our particular problem:

- `CarTitle`
- `CarSubtitle`
- `CarSpecs`
- `CarBadges`
- `CarAttentionGrabber`
- `CarSeller`
- `CarSellerRating`
- `FinanceAvailable`
- `Discounted`

In [27]:
df.drop(columns=[
    "CarTitle",
    "CarSubTitle",
    "CarSpecs",
    "CarBadges",
    "CarAttentionGrabber",
    "CarSeller",
    "CarSellerRating",
    "FinanceAvailable",
    "Discounted"
], inplace=True)

df.head()

,Make,Model,Variant,CarPrice,CarSellerLocation,Year,Reg,BodyType,Miles,EngineVol,...,Transmission,FuelType,NumOwner,ULEZ,FullService,PartService,PartWarranty,FullDealership,FirstYearRoadTax,BrandNew
0,AC,Cobra,NaN,89995.0,Watford,2001.0,X,Convertible,14400.0,4.9,...,Manual,Petrol,5,False,False,False,False,False,False,False
1,AC,Cobra,NaN,92500.0,Chesham,2019.0,T,Convertible,650.0,NaN,...,Manual,Petrol,<NA>,False,False,False,False,False,False,False
2,AC,Cobra,NaN,109995.0,Pulborough,2000.0,X,Convertible,21600.0,3.5,...,Manual,Petrol,3,False,False,False,False,False,False,False
3,AC,Cobra,NaN,124950.0,Oakham,1989.0,F,Convertible,2750.0,NaN,...,Manual,Petrol,<NA>,False,False,False,False,False,False,False
4,AC,Cobra,NaN,124950.0,Oakham,1989.0,E,Convertible,15142.0,5.0,...,Manual,Petrol,<NA>,False,False,False,False,False,False,False

### 2.2.2. Engine Power

There are two metrics of engine power (which the dataset refers to as engine size):

1. Brake Housepower (BHP)
2. Pferdestärke (PS)

The dataset makes use of both. For modelling purposes, it is best that we stick to a single metric. Thus, we use the following relation to convert PS into BHP:

$$
    1 \text{ PS} = 0.98632 \text{ BHP}
$$

In [28]:
df["EngineSizeUnit"].unique()

<ArrowStringArray>
['bhp', nan, 'ps']
Length: 3, dtype: str

In [29]:
df["EngineBHP"] = np.nan

bhp = df["EngineSizeUnit"].str.lower().eq("bhp")
ps = df["EngineSizeUnit"].str.lower().eq("ps")

df.loc[bhp, "EngineBHP"] = df.loc[bhp, "EngineSize"]
df.loc[ps, "EngineBHP"] = 0.98632 * df.loc[ps, "EngineSize"]

df[["Make", "Model", "Variant", "EngineSize", "EngineSizeUnit", "EngineBHP"]].head(20)

      Make       Model    Variant  EngineSize EngineSizeUnit  EngineBHP
0       AC       Cobra        NaN       225.0            bhp   225.0000
1       AC       Cobra        NaN         NaN            NaN        NaN
2       AC       Cobra        NaN         NaN            NaN        NaN
3       AC       Cobra        NaN         NaN            NaN        NaN
4       AC       Cobra        NaN         NaN            NaN        NaN
5       AC       Cobra        NaN         NaN            NaN        NaN
6       AC       Cobra      MK IV         NaN            NaN        NaN
7       AC       Cobra  MK IV CRS       225.0            bhp   225.0000
8   Abarth  124 Spider         GT       167.0            bhp   167.0000
9   Abarth  124 Spider         GT       167.0            bhp   167.0000
10  Abarth  124 Spider         GT       170.0             ps   167.6744
11  Abarth  124 Spider   MultiAir       168.0            bhp   168.0000
12  Abarth  124 Spider   MultiAir       170.0             ps   167.6744
13  Abarth  124 Spider   MultiAir       170.0             ps   167.6744
14  Abarth  124 Spider   MultiAir       168.0            bhp   168.0000
15  Abarth  124 Spider   MultiAir       167.0            bhp   167.0000
16  Abarth  124 Spider   MultiAir       170.0             ps   167.6744
17  Abarth  124 Spider   MultiAir       170.0             ps   167.6744
18  Abarth  124 Spider   MultiAir       168.0            bhp   168.0000
19  Abarth  124 Spider   MultiAir       168.0            bhp   168.0000

For every row which has a recorded `EngineSize` and `EngineSizeUnit`, we have converted to BHP. For rows which have at least one of these missing, we have left `EngineBHP` as NaN. We now drop `EngineSize` and `EngineSizeUnit` since they are redundant. If needed in later analysis, they can easily be recovered using the `clean_car_adverts.csv` we created in the last section.

In [30]:
df.drop(columns=[
    "EngineSize",
    "EngineSizeUnit"
], inplace=True)

df.head()

,Make,Model,Variant,CarPrice,CarSellerLocation,Year,Reg,BodyType,Miles,EngineVol,...,FuelType,NumOwner,ULEZ,FullService,PartService,PartWarranty,FullDealership,FirstYearRoadTax,BrandNew,EngineBHP
0,AC,Cobra,NaN,89995.0,Watford,2001.0,X,Convertible,14400.0,4.9,...,Petrol,5,False,False,False,False,False,False,False,225.0
1,AC,Cobra,NaN,92500.0,Chesham,2019.0,T,Convertible,650.0,NaN,...,Petrol,<NA>,False,False,False,False,False,False,False,NaN
2,AC,Cobra,NaN,109995.0,Pulborough,2000.0,X,Convertible,21600.0,3.5,...,Petrol,3,False,False,False,False,False,False,False,NaN
3,AC,Cobra,NaN,124950.0,Oakham,1989.0,F,Convertible,2750.0,NaN,...,Petrol,<NA>,False,False,False,False,False,False,False,NaN
4,AC,Cobra,NaN,124950.0,Oakham,1989.0,E,Convertible,15142.0,5.0,...,Petrol,<NA>,False,False,False,False,False,False,False,NaN

### 2.2.3. Summary

In this section we have excluded columns from the dataset which are not relevant for our prediction model, and we have cut down the table size by a single column by converting all engine powers into a single unit. We save the resulting dataset to `data/engineered_car_adverts.parquet`.

In [31]:
df.to_parquet("../data/engineered_car_adverts.parquet")

## 2.3. Summary

In this notebook, we have cleaned the dataset, and considered what features we wish to use for modelling. We have created two parquet files from the original dataset.

1. `data/clean_car_adverts.parquet` - the resulting output after cleaning, contains both metrics of engine power as well as data relating to the car adverts themselves.
2. `data/engineered_car_adverts.parquet` - the resulting output after feature engineering with a unified engine power column and after removing the irrelevant columns of the dataset.

Some records still have missing data in some columns. However, at this stage, I think it would be a bad idea to consider either deleting more columns, or deleting records with missing data since we have not yet explored which features are essential for price prediction. This is the goal of the next notebook.